In [1]:
import numpy as np
import pandas as pd

Handling the Data

In [2]:
dataset = pd.read_csv('../crazy_ml_practice_1000.csv')
#X = dataset.iloc[ :, :-1]
X = dataset.drop(columns=['loan_approved', 'annual_salary'])
Y = dataset['loan_approved']
#Y = dataset.iloc[:,:3]
Y
dataset

,id,date,age,gender,city,employment,marital_status,income,years_experience,education_years,...,attendance_pct,screen_time_hours,exercise_days_per_week,projects_completed,social_media_hours,internet_usage,previous_score,lifestyle_score,loan_approved,annual_salary
0,51,2023-02-20,21,Female,Pokhara,Unemployed,Single,124276.0,0.0,13.1,...,67.6,5.6,2,3,0.1,Medium,46.0,42.69,Yes,250000.0
1,426,2024-03-01,26,Female,Butwal,Employed,Single,63947.0,3.0,11.9,...,86.5,3.1,7,3,2.9,Medium,67.2,66.78,No,250000.0
2,205,2023-07-24,56,Male,Bhaktapur,Unemployed,Married,185104.0,27.9,11.3,...,55.9,5.7,4,6,4.2,Medium,46.4,38.57,No,250000.0
3,86,2023-03-27,65,Male,Pokhara,Employed,Single,70835.0,45.0,14.4,...,93.1,6.1,5,3,3.6,High,85.5,64.58,Yes,250000.0
4,799,2025-03-09,58,Female,Biratnagar,Self-employed,Married,12455.0,40.3,12.7,...,100.0,6.9,1,3,3.1,Medium,53.5,46.43,No,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,989,2025-09-15,47,Male,Chitwan,Self-employed,Single,26340.0,27.0,14.8,...,67.0,4.3,1,3,2.8,Medium,59.9,41.39,No,250000.0
1004,323,2023-11-19,53,Male,Butwal,Employed,Single,94899.0,20.7,12.0,...,100.0,9.2,4,2,2.3,Medium,52.0,73.02,No,250000.0
1005,383,2024-01-18,47,Female,Butwal,Employed,Divorced,47772.0,29.7,17.1,...,87.0,6.7,2,4,4.3,Medium,54.0,60.22,Yes,250000.0
1006,366,2024-01-01,44,Female,Chitwan,Employed,Single,46262.0,14.1,11.8,...,56.3,3.5,2,4,4.8,High,98.9,24.40,Yes,250000.0
1007,511,2024-05-25,70,Male,Butwal,Employed,Single,21004.0,45.0,14.3,...,68.4,2.9,4,4,1.9,Medium,91.0,50.85,Yes,250000.0

Encoding Categorical Data

In [19]:
# from sklearn.impute import SimpleImputer

# imputer = SimpleImputer(
#     missing_values=np.nan,
#     strategy="mean"
# )

# X.iloc[:, 1:3] = imputer.fit_transform(X.iloc[:, 1:3])

For Numerical Column Encoding

In [7]:
from sklearn.impute import SimpleImputer

numeric_columns = [
    'income',
    'education_years',
    'credit_score',
    'debt',
    'study_hours',
    'attendance_pct'
]

imputer = SimpleImputer(strategy='mean')

dataset[numeric_columns] = imputer.fit_transform(
    dataset[numeric_columns]
)
imputer

SimpleImputer()

Encoding Categorical Data with changing the gender like male 1 female 0

In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_X = LabelEncoder()

X['gender'] = labelencoder_X.fit_transform(X['gender'])
labelencoder_X

LabelEncoder()

In [5]:
onehotencoder = OneHotEncoder(
    handle_unknown='ignore',
    sparse_output=False
)

X_city = onehotencoder.fit_transform(X[['city']])
X_city

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]], shape=(1008, 7))

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=0
)

In [9]:
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(806, 23)
(202, 23)
(806,)
(202,)

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=0
)
X_test

,id,date,age,gender,city,employment,marital_status,income,years_experience,education_years,...,study_hours,sleep_hours,attendance_pct,screen_time_hours,exercise_days_per_week,projects_completed,social_media_hours,internet_usage,previous_score,lifestyle_score
800,563,2024-07-16,19,0,Butwal,Student,Married,35926.0,0.0,15.0,...,4.2,6.1,98.6,4.7,1,1,0.5,High,86.2,55.81
311,231,2023-08-19,66,0,Kathmandu,Unemployed,Single,31869.0,43.5,11.6,...,1.1,5.9,76.3,7.4,5,4,3.2,Low,71.3,42.94
85,862,2025-05-11,36,1,Bhaktapur,Unemployed,Married,19936.0,14.0,14.2,...,15.5,7.4,74.1,4.8,1,5,4.4,High,53.1,88.49
435,229,2023-08-17,66,0,Chitwan,Employed,Single,34644.0,43.4,16.2,...,1.3,6.4,87.7,6.8,0,2,1.1,Medium,100.0,36.35
204,730,2024-12-30,43,0,Butwal,Employed,Married,58517.0,12.1,13.1,...,7.4,6.7,64.1,4.0,2,5,3.5,High,72.2,50.66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
783,635,2024-09-26,66,0,Pokhara,Unemployed,Single,46609.0,34.0,12.5,...,4.4,8.3,87.5,1.0,0,8,6.2,High,68.4,60.91
231,700,2024-11-30,57,1,Butwal,Student,Single,34520.0,37.6,15.2,...,5.6,8.9,98.2,6.0,5,3,0.8,Medium,100.0,73.85
5,909,2025-06-27,35,1,Butwal,Self-employed,Single,57409.0,12.4,13.0,...,3.6,8.4,74.0,7.6,6,3,3.6,Medium,42.7,52.55
452,454,2024-03-29,49,1,Pokhara,Student,Single,34999.0,30.0,8.4,...,3.4,6.8,NaN,7.5,3,2,3.6,Medium,57.1,58.14
683,331,2023-11-27,42,0,Lalitpur,Student,Married,12000.0,21.6,9.3,...,11.3,6.5,87.6,5.1,4,3,3.7,Medium,74.8,74.87